import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next js Bhavesh Product",
    template: "%s | Product",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "pink", height: "100px" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "gray", height: "100px" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
